# Nombre de la aplicación
spring.application.name=clicktech-back

# Puerto del servidor
server.port=8080

# Configuración de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/click_tech?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Spring DevTools
spring.devtools.restart.enabled=true

# Configuración JWT (expiración: 5 minutos = 300,000 ms)
jwt.secret=ClickTech2026SecretKeyParaFirmarTokensJWT_DebeSerLargaYSegura!
jwt.expiration=300000
